package ws.model;
// Generated 09-may-2015 16:53:31 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tpromociones generated by hbm2java
 */
@Entity
@Table(name="tpromociones"
    ,catalog="pagaaquidb"
)@XmlRootElement

public class Tpromociones  implements java.io.Serializable {


     private Integer id;
     private String titulo;
     private String descripcion;

    public Tpromociones() {
    }

    public Tpromociones(String titulo, String descripcion) {
       this.titulo = titulo;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="titulo", nullable=false)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


